name: CI

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - v[012].[0-9]+.[0-9]+

jobs:
  test:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Run Scalastyle
        run: |
          sbt scalastyle
      - name: Run Tests with Coverage
        run: |
          sbt coverage test coverageReport
