name: CI

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - v[012].[0-9]+.[0-9]+
      - main

jobs:
  scalastyle:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Run Scalastyle
        run: |
          sbt scalastyle
      - uses: actions/upload-artifact@v2
        with:
          name: scalastyle
          path: |
            target/scalastyle-result.xml
  scoverage:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Cache SBT
        uses: actions/cache@v2
        with:
          path: |
            ~/.ivy2/cache
            ~/.sbt
          key: ${{ runner.os }}-sbt-${{ hashFiles('**/build.sbt') }}
      - name: Run Tests with Coverage
        run: |
          sbt coverage test coverageReport
      - uses: actions/upload-artifact@v2
        with:
          name: scoverage
          path: |
            target/scala-2.12/scoverage-report/scoverage.xml
      